/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMarsRouteImport } from './routes/_app.mars'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppEarthEventsRouteImport } from './routes/_app.earth-events'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAsteroidsRouteImport } from './routes/_app.asteroids'
import { Route as AppApodRouteImport } from './routes/_app.apod'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMarsRoute = AppMarsRouteImport.update({
  id: '/mars',
  path: '/mars',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppEarthEventsRoute = AppEarthEventsRouteImport.update({
  id: '/earth-events',
  path: '/earth-events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAsteroidsRoute = AppAsteroidsRouteImport.update({
  id: '/asteroids',
  path: '/asteroids',
  getParentRoute: () => AppRoute,
} as any)
const AppApodRoute = AppApodRouteImport.update({
  id: '/apod',
  path: '/apod',
  getParentRoute: () => AppRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apod': typeof AppApodRoute
  '/asteroids': typeof AppAsteroidsRoute
  '/dashboard': typeof AppDashboardRoute
  '/earth-events': typeof AppEarthEventsRoute
  '/favorites': typeof AppFavoritesRoute
  '/mars': typeof AppMarsRoute
  '/profile': typeof AppProfileRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apod': typeof AppApodRoute
  '/asteroids': typeof AppAsteroidsRoute
  '/dashboard': typeof AppDashboardRoute
  '/earth-events': typeof AppEarthEventsRoute
  '/favorites': typeof AppFavoritesRoute
  '/mars': typeof AppMarsRoute
  '/profile': typeof AppProfileRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/apod': typeof AppApodRoute
  '/_app/asteroids': typeof AppAsteroidsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/earth-events': typeof AppEarthEventsRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/mars': typeof AppMarsRoute
  '/_app/profile': typeof AppProfileRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/apod'
    | '/asteroids'
    | '/dashboard'
    | '/earth-events'
    | '/favorites'
    | '/mars'
    | '/profile'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/apod'
    | '/asteroids'
    | '/dashboard'
    | '/earth-events'
    | '/favorites'
    | '/mars'
    | '/profile'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/apod'
    | '/_app/asteroids'
    | '/_app/dashboard'
    | '/_app/earth-events'
    | '/_app/favorites'
    | '/_app/mars'
    | '/_app/profile'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mars': {
      id: '/_app/mars'
      path: '/mars'
      fullPath: '/mars'
      preLoaderRoute: typeof AppMarsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/earth-events': {
      id: '/_app/earth-events'
      path: '/earth-events'
      fullPath: '/earth-events'
      preLoaderRoute: typeof AppEarthEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asteroids': {
      id: '/_app/asteroids'
      path: '/asteroids'
      fullPath: '/asteroids'
      preLoaderRoute: typeof AppAsteroidsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apod': {
      id: '/_app/apod'
      path: '/apod'
      fullPath: '/apod'
      preLoaderRoute: typeof AppApodRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApodRoute: typeof AppApodRoute
  AppAsteroidsRoute: typeof AppAsteroidsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEarthEventsRoute: typeof AppEarthEventsRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppMarsRoute: typeof AppMarsRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApodRoute: AppApodRoute,
  AppAsteroidsRoute: AppAsteroidsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEarthEventsRoute: AppEarthEventsRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppMarsRoute: AppMarsRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
